// <auto-generated />
using System;
using DataMount.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataMount.Infra.Migrations
{
    [DbContext(typeof(AppDbContext<Guid>))]
    [Migration("20260527120425_AddProjectModels")]
    partial class AddProjectModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataMount.Domain.Models.Identity.Account<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text")
                        .HasColumnName("block_reason");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IdentifierContactId")
                        .HasColumnType("uuid")
                        .HasColumnName("identifier_contact_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("account_type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasAlternateKey("IdentifierContactId", "OwnerId")
                        .HasName("ak_accounts_identifier_contact_id_owner_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_accounts_owner_id");

                    b.ToTable("accounts", (string)null);

                    b.HasDiscriminator<string>("account_type").HasValue("Account<Guid>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.Contact<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasAlternateKey("Type", "Value")
                        .HasName("ak_contacts_type_value");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_contacts_owner_id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.LoginAttempt<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_login_attempts");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_login_attempts_account_id");

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.Session<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_sessions_account_id");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_attempt_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.User<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("OnboardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarded_at");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.Form<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_forms");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_forms_project_id");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.FormItem<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("item_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("item_type");

                    b.HasKey("Id")
                        .HasName("pk_form_items");

                    b.HasIndex("FormId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_form_items_form_id_path");

                    b.ToTable("form_items", (string)null);

                    b.HasDiscriminator<string>("item_type").HasValue("FormItem<Guid>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.Project<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.CredentialAccount<System.Guid>", b =>
                {
                    b.HasBaseType("DataMount.Domain.Models.Identity.Account<System.Guid>");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasDiscriminator().HasValue("credential");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.OAuthAccount<System.Guid>", b =>
                {
                    b.HasBaseType("DataMount.Domain.Models.Identity.Account<System.Guid>");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.ToTable("accounts", (string)null);

                    b.HasDiscriminator().HasValue("oauth");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.TextQuestion<System.Guid>", b =>
                {
                    b.HasBaseType("DataMount.Domain.Models.Projects.FormItem<System.Guid>");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.ToTable("form_items", (string)null);

                    b.HasDiscriminator().HasValue("question");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.Account<System.Guid>", b =>
                {
                    b.HasOne("DataMount.Domain.Models.Identity.Contact<System.Guid>", "IdentifierContact")
                        .WithMany()
                        .HasForeignKey("IdentifierContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_contacts_identifier_contact_id");

                    b.HasOne("DataMount.Domain.Models.Identity.User<System.Guid>", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_users_owner_id");

                    b.Navigation("IdentifierContact");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.Contact<System.Guid>", b =>
                {
                    b.HasOne("DataMount.Domain.Models.Identity.User<System.Guid>", "Owner")
                        .WithMany("Contacts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.LoginAttempt<System.Guid>", b =>
                {
                    b.HasOne("DataMount.Domain.Models.Identity.Account<System.Guid>", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_login_attempts_account_guid_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.Session<System.Guid>", b =>
                {
                    b.HasOne("DataMount.Domain.Models.Identity.Account<System.Guid>", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_account_guid_account_id");

                    b.HasOne("DataMount.Domain.Models.Identity.LoginAttempt<System.Guid>", "Attempt")
                        .WithOne()
                        .HasForeignKey("DataMount.Domain.Models.Identity.Session<System.Guid>", "AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sessions_login_attempts_attempt_id");

                    b.Navigation("Account");

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.Form<System.Guid>", b =>
                {
                    b.HasOne("DataMount.Domain.Models.Projects.Project<System.Guid>", "Project")
                        .WithMany("Forms")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_forms_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.FormItem<System.Guid>", b =>
                {
                    b.HasOne("DataMount.Domain.Models.Projects.Form<System.Guid>", "Form")
                        .WithMany("FormItems")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_form_items_forms_form_id");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Identity.User<System.Guid>", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.Form<System.Guid>", b =>
                {
                    b.Navigation("FormItems");
                });

            modelBuilder.Entity("DataMount.Domain.Models.Projects.Project<System.Guid>", b =>
                {
                    b.Navigation("Forms");
                });
#pragma warning restore 612, 618
        }
    }
}
