// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_data

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  sql.NullString
	Photo     sql.NullString
	AddedAt   time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
