// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package user_data

import (
	"context"
)

const listUsers = `-- name: ListUsers :many
SELECT
    id, first_name, last_name, photo, added_at, updated_at, deleted_at
FROM
    users
WHERE
    deleted_at IS NULL
ORDER BY
    added_at DESC,
    updated_at DESC
LIMIT
    $2
OFFSET
    $1
`

type ListUsersParams struct {
	Page int32
	Size int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Page, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Photo,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
