name: Trigger Deployments

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Docker publish'
    types:
      - completed

jobs:
  deploy_render:
    runs-on: ubuntu-latest
    name: Deploy on render
    env:
      DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - name: Trigger deployment hook
        run: |
          curl -L {{ env.DEPLOY_HOOK }}